In [ ]:
import pandas as pd

In [ ]:
import pandas as pd

df = pd.read_excel('/content/Online Retail.xlsx')

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [ ]:
df.sample(15)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
433568,573931,23084,RABBIT NIGHT LIGHT,12,2011-11-02 10:16:00,2.08,16884.0,United Kingdom
306342,563748,23310,BUBBLEGUM RING ASSORTED,72,2011-08-19 10:06:00,0.42,16170.0,United Kingdom
25492,538370,21531,RED RETROSPOT SUGAR JAM BOWL,1,2010-12-12 11:06:00,2.55,16923.0,United Kingdom
170032,551275,21936,RED RETROSPOT PICNIC BAG,5,2011-04-27 13:03:00,2.95,13285.0,United Kingdom
232276,557311,21618,4 WILDFLOWER BOTANICAL CANDLES,2,2011-06-19 15:36:00,3.75,15700.0,United Kingdom
369384,569027,22713,CARD I LOVE LONDON,12,2011-09-30 10:19:00,0.42,13089.0,United Kingdom
341184,566736,22704,WRAP RED APPLES,25,2011-09-14 14:19:00,0.42,12726.0,France
483662,577506,21670,BLUE SPOT CERAMIC DRAWER KNOB,1,2011-11-20 12:40:00,1.45,13212.0,United Kingdom
15710,537640,22367,CHILDRENS APRON SPACEBOY DESIGN,15,2010-12-07 15:31:00,5.06,NaN,United Kingdom
180142,552305,23208,LUNCH BAG VINTAGE LEAF DESIGN,10,2011-05-08 15:16:00,1.65,14341.0,United Kingdom
199185,554088,21288,STRIPEY CHOCOLATE NESTING BOXES,12,2011-05-22 12:12:00,2.95,16801.0,United Kingdom
479614,577172,23230,WRAP ALPHABET DESIGN,25,2011-11-18 10:56:00,0.42,17760.0,United Kingdom
483665,577506,23319,BOX OF 6 MINI 50'S CRACKERS,3,2011-11-20 12:40:00,2.49,13212.0,United Kingdom
503423,578926,23439,HAND WARMER RED LOVE HEART,2,2011-11-27 12:24:00,2.10,18156.0,United Kingdom
136879,547995,35823P,NaN,-12,2011-03-29 10:20:00,0.00,NaN,United Kingdom

In [ ]:
df.shape

(541909, 8)

In [ ]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [ ]:
df.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

In [ ]:
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

Total rows: 541909
Total columns: 8

In [ ]:
df["Description"].head(20)

0      WHITE HANGING HEART T-LIGHT HOLDER
1                     WHITE METAL LANTERN
2          CREAM CUPID HEARTS COAT HANGER
3     KNITTED UNION FLAG HOT WATER BOTTLE
4          RED WOOLLY HOTTIE WHITE HEART.
5            SET 7 BABUSHKA NESTING BOXES
6       GLASS STAR FROSTED T-LIGHT HOLDER
7                  HAND WARMER UNION JACK
8               HAND WARMER RED POLKA DOT
9           ASSORTED COLOUR BIRD ORNAMENT
10             POPPY'S PLAYHOUSE BEDROOM
11              POPPY'S PLAYHOUSE KITCHEN
12      FELTCRAFT PRINCESS CHARLOTTE DOLL
13                IVORY KNITTED MUG COSY
14     BOX OF 6 ASSORTED COLOUR TEASPOONS
15          BOX OF VINTAGE JIGSAW BLOCKS
16         BOX OF VINTAGE ALPHABET BLOCKS
17               HOME BUILDING BLOCK WORD
18               LOVE BUILDING BLOCK WORD
19            RECIPE BOX WITH METAL HEART
Name: Description, dtype: object

### Project Dataset Summary

The Online Retail dataset contains 541,909 transaction records and 8 columns. It includes invoice numbers, product codes and descriptions, quantities, invoice dates, unit prices, customer IDs, and countries. The dataset can be used to analyze product sales, customer purchasing behavior, country-wise sales, and monthly sales trends. Before analysis, data quality issues such as missing values, cancellations, returns, and zero or negative quantities and prices must be investigated carefully.

In [ ]:
df_selected = df[
    [
        "InvoiceNo",
        "StockCode",
        "Description",
        "Quantity",
        "UnitPrice",
        "CustomerID",
        "Country"
    ]
]

df_selected.head()

,InvoiceNo,StockCode,Description,Quantity,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,3.39,17850.0,United Kingdom

In [ ]:
df_first10 = df.head(10).copy()

df_first10

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [ ]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

In [ ]:
df[["Country", "Description"]].describe()

               Country                         Description
count           541909                              540455
unique              38                                4223
top     United Kingdom  WHITE HANGING HEART T-LIGHT HOLDER
freq            495478                                2369

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [ ]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [ ]:
distinct_counts = pd.Series({
    "Distinct invoices": df["InvoiceNo"].nunique(),
    "Distinct products": df["StockCode"].nunique(),
    "Distinct countries": df["Country"].nunique(),
    "Identified customers": df["CustomerID"].nunique()
})

distinct_counts

Distinct invoices       25900
Distinct products        4070
Distinct countries         38
Identified customers     4372
dtype: int64

In [ ]:
countries = df["Country"].unique()

print(countries)
print("Number of countries:", len(countries))

['United Kingdom' 'France' 'Australia' 'Netherlands' 'Germany' 'Norway'
 'EIRE' 'Switzerland' 'Spain' 'Poland' 'Portugal' 'Italy' 'Belgium'
 'Lithuania' 'Japan' 'Iceland' 'Channel Islands' 'Denmark' 'Cyprus'
 'Sweden' 'Austria' 'Israel' 'Finland' 'Bahrain' 'Greece' 'Hong Kong'
 'Singapore' 'Lebanon' 'United Arab Emirates' 'Saudi Arabia'
 'Czech Republic' 'Canada' 'Unspecified' 'Brazil' 'USA'
 'European Community' 'Malta' 'RSA']
Number of countries: 38

In [ ]:
country_counts = df["Country"].value_counts()

country_counts.head(10)

Country
United Kingdom    495478
Germany             9495
France              8557
EIRE                8196
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         2002
Portugal            1519
Australia           1259
Name: count, dtype: int64

In [ ]:
dataset_summary = pd.DataFrame({
    "Total Rows": [df.shape[0]],
    "Total Columns": [df.shape[1]],
    "Unique Products": [df["StockCode"].nunique()],
    "Unique Invoices": [df["InvoiceNo"].nunique()]
})

dataset_summary

   Total Rows  Total Columns  Unique Products  Unique Invoices
0      541909              8             4070            25900

In [ ]:
dataset_profile = pd.DataFrame({
    "Metric": [
        "Total Rows",
        "Total Columns",
        "Unique Products",
        "Unique Invoices",
        "Unique Countries",
        "Identified Customers",
        "Missing Descriptions",
        "Missing CustomerIDs",
        "Total Missing Cells"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        df["StockCode"].nunique(),
        df["InvoiceNo"].nunique(),
        df["Country"].nunique(),
        df["CustomerID"].nunique(),
        df["Description"].isnull().sum(),
        df["CustomerID"].isnull().sum(),
        df.isnull().sum().sum()
    ]
})

dataset_profile

                 Metric   Value
0            Total Rows  541909
1         Total Columns       8
2       Unique Products    4070
3       Unique Invoices   25900
4      Unique Countries      38
5  Identified Customers    4372
6  Missing Descriptions    1454
7   Missing CustomerIDs  135080
8   Total Missing Cells  136534

In [ ]:
dataset_profile.to_csv(
    "/content/dataset_profile.csv",
    index=False
)

print("Dataset profile exported successfully!")

Dataset profile exported successfully!

In [ ]:
df_invoice_dates = df[["InvoiceNo", "InvoiceDate"]]

df_invoice_dates.head()

  InvoiceNo         InvoiceDate
0    536365 2010-12-01 08:26:00
1    536365 2010-12-01 08:26:00
2    536365 2010-12-01 08:26:00
3    536365 2010-12-01 08:26:00
4    536365 2010-12-01 08:26:00

In [ ]:
df.iloc[10]

InvoiceNo                          536367
StockCode                           22745
Description    POPPY'S PLAYHOUSE BEDROOM
Quantity                                6
InvoiceDate           2010-12-01 08:34:00
UnitPrice                             2.1
CustomerID                        13047.0
Country                    United Kingdom
Name: 10, dtype: object

In [ ]:
df.loc[5:10, ["InvoiceNo", "Description", "Quantity", "Country"]]

   InvoiceNo                        Description  Quantity         Country
5     536365       SET 7 BABUSHKA NESTING BOXES         2  United Kingdom
6     536365  GLASS STAR FROSTED T-LIGHT HOLDER         6  United Kingdom
7     536366             HAND WARMER UNION JACK         6  United Kingdom
8     536366          HAND WARMER RED POLKA DOT         6  United Kingdom
9     536367      ASSORTED COLOUR BIRD ORNAMENT        32  United Kingdom
10    536367         POPPY'S PLAYHOUSE BEDROOM          6  United Kingdom

In [ ]:
df_quantity_gt10 = df[df["Quantity"] > 10]

df_quantity_gt10.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France

In [ ]:
df_price_gt50 = df[df["UnitPrice"] > 50]

df_price_gt50.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
246,536392,22827,RUSTIC SEVENTEEN DRAWER SIDEBOARD,1,2010-12-01 10:29:00,165.00,13705.0,United Kingdom
1665,536544,22769,CHALKBOARD KITCHEN ORGANISER,1,2010-12-01 14:32:00,51.02,NaN,United Kingdom
1814,536544,DOT,DOTCOM POSTAGE,1,2010-12-01 14:32:00,569.77,NaN,United Kingdom
2738,536592,22503,CABIN BAG VINTAGE PAISLEY,1,2010-12-01 17:06:00,59.53,NaN,United Kingdom
3041,536592,DOT,DOTCOM POSTAGE,1,2010-12-01 17:06:00,607.49,NaN,United Kingdom

In [ ]:
df_france = df[df["Country"] == "France"]

df_france.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France
30,536370,21883,STARS GIFT TAPE,24,2010-12-01 08:45:00,0.65,12583.0,France

In [ ]:
# Find the five countries with the most transactions
top_5_countries = df["Country"].value_counts().head(5).index

# Filter transactions belonging to those countries
df_top5_countries = df[df["Country"].isin(top_5_countries)]

df_top5_countries.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df_quantity_5_20 = df[df["Quantity"].between(5, 20)]

df_quantity_5_20.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [ ]:
df_query_result = df.query("Quantity > 10 and UnitPrice > 5")

df_query_result.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
65,536374,21258,VICTORIAN SEWING BOX LARGE,32,2010-12-01 09:09:00,10.95,15100.0,United Kingdom
150,536382,22926,IVORY GIANT GARDEN THERMOMETER,12,2010-12-01 09:45:00,5.95,16098.0,United Kingdom
880,536477,22423,REGENCY CAKESTAND 3 TIER,16,2010-12-01 12:27:00,10.95,16210.0,United Kingdom
1218,536531,15056N,EDWARDIAN PARASOL NATURAL,12,2010-12-01 13:23:00,5.95,15485.0,United Kingdom
1219,536531,15056BL,EDWARDIAN PARASOL BLACK,12,2010-12-01 13:23:00,5.95,15485.0,United Kingdom

In [ ]:
df_top20_prices = df.sort_values(
    by="UnitPrice",
    ascending=False
).head(20)

df_top20_prices

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
222681,C556445,M,Manual,-1,2011-06-10 15:31:00,38970.00,15098.0,United Kingdom
524602,C580605,AMAZONFEE,AMAZON FEE,-1,2011-12-05 11:36:00,17836.46,NaN,United Kingdom
43702,C540117,AMAZONFEE,AMAZON FEE,-1,2011-01-05 09:55:00,16888.02,NaN,United Kingdom
43703,C540118,AMAZONFEE,AMAZON FEE,-1,2011-01-05 09:57:00,16453.71,NaN,United Kingdom
16356,C537651,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:49:00,13541.33,NaN,United Kingdom
15016,C537630,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:04:00,13541.33,NaN,United Kingdom
15017,537632,AMAZONFEE,AMAZON FEE,1,2010-12-07 15:08:00,13541.33,NaN,United Kingdom
16232,C537644,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:34:00,13474.79,NaN,United Kingdom
524601,C580604,AMAZONFEE,AMAZON FEE,-1,2011-12-05 11:35:00,11586.50,NaN,United Kingdom
299982,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom
446533,C574902,AMAZONFEE,AMAZON FEE,-1,2011-11-07 15:21:00,8286.22,NaN,United Kingdom
173277,C551685,POST,POSTAGE,-1,2011-05-03 12:51:00,8142.75,16029.0,United Kingdom
173382,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029.0,United Kingdom
342635,C566899,AMAZONFEE,AMAZON FEE,-1,2011-09-15 13:53:00,7427.97,NaN,United Kingdom
191386,C553355,AMAZONFEE,AMAZON FEE,-1,2011-05-16 13:58:00,7006.83,NaN,United Kingdom
173391,C551699,M,Manual,-1,2011-05-03 14:12:00,6930.00,16029.0,United Kingdom
287150,C562086,AMAZONFEE,AMAZON FEE,-1,2011-08-02 12:27:00,6721.37,NaN,United Kingdom
16357,C537652,AMAZONFEE,AMAZON FEE,-1,2010-12-07 15:51:00,6706.71,NaN,United Kingdom
312246,C564341,AMAZONFEE,AMAZON FEE,-1,2011-08-24 14:53:00,6662.51,NaN,United Kingdom
262414,C559917,AMAZONFEE,AMAZON FEE,-1,2011-07-13 15:21:00,6497.47,NaN,United Kingdom

In [ ]:
# Keep an untouched copy of the original dataset
df_raw = df.copy(deep=True)

# Create a separate DataFrame for our work
df_work = df_raw.copy(deep=True)

# Verify their dimensions
print("Original df shape:", df.shape)
print("Raw backup shape:", df_raw.shape)
print("Working copy shape:", df_work.shape)

Original df shape: (541909, 8)
Raw backup shape: (541909, 8)
Working copy shape: (541909, 8)

In [ ]:
df_work.rename(
    columns={"Description": "ProductDescription"},
    inplace=True
)

df_work.columns

Index(['InvoiceNo', 'StockCode', 'ProductDescription', 'Quantity',
       'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [ ]:
# Calculate revenue for each transaction line
df_work["Revenue"] = df_work["Quantity"] * df_work["UnitPrice"]

# Display the calculation for the first 10 rows
df_work[["Quantity", "UnitPrice", "Revenue"]].head(10)

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34
5         2       7.65    15.30
6         6       4.25    25.50
7         6       1.85    11.10
8         6       1.85    11.10
9        32       1.69    54.08

In [ ]:
# Identify cancellation invoices
is_cancellation = (
    df_work["InvoiceNo"]
    .astype("string")
    .str.startswith("C", na=False)
)

# Give every row a default category
df_work["TransactionType"] = "Other/Invalid"

# Classify cancellations first
df_work.loc[
    is_cancellation,
    "TransactionType"
] = "Cancellation"

# Classify negative quantities outside cancellation invoices
df_work.loc[
    (~is_cancellation) & (df_work["Quantity"] < 0),
    "TransactionType"
] = "Return"

# Classify positive quantities with positive prices
df_work.loc[
    (~is_cancellation)
    & (df_work["Quantity"] > 0)
    & (df_work["UnitPrice"] > 0),
    "TransactionType"
] = "Positive Sale"

# Inspect the classifications
print(df_work[
    ["InvoiceNo", "Quantity", "UnitPrice", "Revenue", "TransactionType"]
].head(10))

print("\nTransaction type counts:")
print(df_work["TransactionType"].value_counts())

  InvoiceNo  Quantity  UnitPrice  Revenue TransactionType
0    536365         6       2.55    15.30   Positive Sale
1    536365         6       3.39    20.34   Positive Sale
2    536365         8       2.75    22.00   Positive Sale
3    536365         6       3.39    20.34   Positive Sale
4    536365         6       3.39    20.34   Positive Sale
5    536365         2       7.65    15.30   Positive Sale
6    536365         6       4.25    25.50   Positive Sale
7    536366         6       1.85    11.10   Positive Sale
8    536366         6       1.85    11.10   Positive Sale
9    536367        32       1.69    54.08   Positive Sale

Transaction type counts:
TransactionType
Positive Sale    530104
Cancellation       9288
Return             1336
Other/Invalid      1181
Name: count, dtype: int64

In [ ]:
df_work["IsIdentifiedCustomer"] = df_work["CustomerID"].notna()

df_work[["CustomerID", "IsIdentifiedCustomer"]].head(10)

   CustomerID  IsIdentifiedCustomer
0     17850.0                  True
1     17850.0                  True
2     17850.0                  True
3     17850.0                  True
4     17850.0                  True
5     17850.0                  True
6     17850.0                  True
7     17850.0                  True
8     17850.0                  True
9     13047.0                  True

In [ ]:
# Convert InvoiceDate to Pandas datetime
df_work["InvoiceDate"] = pd.to_datetime(df_work["InvoiceDate"])

# Verify the data type
print(df_work["InvoiceDate"].dtype)

# Display a few dates
df_work["InvoiceDate"].head()

datetime64[ns]

0   2010-12-01 08:26:00
1   2010-12-01 08:26:00
2   2010-12-01 08:26:00
3   2010-12-01 08:26:00
4   2010-12-01 08:26:00
Name: InvoiceDate, dtype: datetime64[ns]

In [ ]:
# Convert identifier and country columns to string
df_work["InvoiceNo"] = df_work["InvoiceNo"].astype("string")
df_work["StockCode"] = df_work["StockCode"].astype("string")
df_work["Country"] = df_work["Country"].astype("string")

# Verify the data types
print(df_work[["InvoiceNo", "StockCode", "Country"]].dtypes)

# Display the first five rows
df_work[["InvoiceNo", "StockCode", "Country"]].head()

InvoiceNo    string[python]
StockCode    string[python]
Country      string[python]
dtype: object

  InvoiceNo StockCode         Country
0    536365    85123A  United Kingdom
1    536365     71053  United Kingdom
2    536365    84406B  United Kingdom
3    536365    84029G  United Kingdom
4    536365    84029E  United Kingdom

In [1]:
# Define the desired column order
column_order = [
    "InvoiceNo",
    "InvoiceDate",
    "StockCode",
    "ProductDescription",
    "CustomerID",
    "IsIdentifiedCustomer",
    "Country",
    "Quantity",
    "UnitPrice",
    "Revenue",
    "TransactionType"
]

# Reorder the columns in the working DataFrame
df_work = df_work[column_order]

# Verify the new order
print(df_work.columns.tolist())

# Display the first five rows
df_work.head()

NameError: name 'df_work' is not defined

In [3]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import os

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if file == "Online Retail.xlsx":
            print(os.path.join(root, file))

In [4]:
import os

print(os.path.exists(
    "/content/drive/MyDrive/Online Retail.xlsx"
))

False

In [5]:
import os

path = "/content/drive/MyDrive"

print(os.listdir(path)[:50])

['Colab Notebooks', 'Untitled spreadsheet.gsheet', '411522106004.pdf', 'Aswini V.pdf', 'AccountStatement1738072034641.pdf', 'Executed programs.docx', 'certificate_673ddcd5-e4a8-434b-9342-056cb8ca3f18.png', 'AccountStatement1742389549346.pdf', 'AccountStatement1742822001505.pdf', 'AccountStatement1744595155789.pdf', 'Batch 7.docx', '20250704_150531.jpg', 'Aswini.V_Resume.png', 'Aswini.V_Resume (1).png', '_V. Aswini_Resume_1_IT.pdf', 'MINI PROJECT.pptx', '_V. Aswini_Resume_1.pdf', 'Resume', '20250916_083927.jpg', 'Untitled form (2).gform', 'Untitled form (1).gform', 'Untitled form.gform', 'IMG-20251009-WA0013.jpg', 'IMG-20251009-WA0006.jpg', 'Aswini_Resume_IT[1] (1).pdf', 'Aswini_Resume_IT[1].pdf', 'Document from Aswini.pdf', 'Aswini_Resume_Core.pdf', 'Aswini_Resume_Ats.pdf', 'LOGIN DETAILS FINAL YR.xlsx', 'Document from Aswini (1)', 'Document from Aswini', 'Dementia Detection and Severity Classification from Brain MRI Using CNN-Based Image Processing', 'BATCH - 2.pptx', 'Copy of BATCH - 2.pptx', 'BATCH - 2.gslides', 'Copy of BATCH - 2.gslides', 'BATCH 2.pptx', 'IMG-20260417-WA0105.jpg', 'umis no -Engg 2023.gsheet', 'ASWINI V- PPT.pptx', 'Aswini v - ppt 2.pptx', 'JAVA - OPERATORS.pptx', 'JAVA - OPERATORS - ppt3.pptx', 'ASWINI V - FULL PPT 2.pptx', 'ASWINI V- full PPT .pptx', 'Copy of OOPS Concepts in Java.pptx', 'OOPS Concepts in Java.gslides', 'OOPS Concepts in Java.pptx', 'java part 3 full ppt.pptx']

In [6]:
import os

found = False

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for file in files:
        if "Online Retail" in file:
            print(os.path.join(root, file))
            found = True

if not found:
    print("Excel file not found in Google Drive")

/content/drive/MyDrive/Online Retail.xlsx

In [7]:
import pandas as pd

df = pd.read_excel(
    "/content/drive/MyDrive/Online Retail.xlsx"
)

df_raw = df.copy(deep=True)
df_work = df_raw.copy(deep=True)

print("Original dataset:", df.shape)
print("Raw backup:", df_raw.shape)
print("Working copy:", df_work.shape)

Original dataset: (541909, 8)
Raw backup: (541909, 8)
Working copy: (541909, 8)

In [8]:
df_work.rename(
    columns={"Description": "ProductDescription"},
    inplace=True
)

print(df_work.columns.tolist())

['InvoiceNo', 'StockCode', 'ProductDescription', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

In [9]:
df_work["Revenue"] = df_work["Quantity"] * df_work["UnitPrice"]

df_work[["Quantity", "UnitPrice", "Revenue"]].head(10)

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34
5         2       7.65    15.30
6         6       4.25    25.50
7         6       1.85    11.10
8         6       1.85    11.10
9        32       1.69    54.08

In [10]:
# Rule 1: Invoice numbers starting with C are cancellations
is_cancellation = (
    df_work["InvoiceNo"].astype("string").str.startswith("C", na=False)
)

df_work["TransactionType"] = "Other/Invalid"

# Rule 2: Cancellation
df_work.loc[is_cancellation, "TransactionType"] = "Cancellation"

# Rule 3: Negative quantity, excluding cancellations
df_work.loc[
    (~is_cancellation) & (df_work["Quantity"] < 0),
    "TransactionType"
] = "Return"

# Rule 4: Positive quantity and positive price, excluding cancellations
df_work.loc[
    (~is_cancellation)
    & (df_work["Quantity"] > 0)
    & (df_work["UnitPrice"] > 0),
    "TransactionType"
] = "Positive Sale"

# Display sample records
print(df_work[[
    "InvoiceNo", "Quantity", "UnitPrice",
    "Revenue", "TransactionType"
]].head(10))

print("\nTransaction type counts:")
print(df_work["TransactionType"].value_counts())

  InvoiceNo  Quantity  UnitPrice  Revenue TransactionType
0    536365         6       2.55    15.30   Positive Sale
1    536365         6       3.39    20.34   Positive Sale
2    536365         8       2.75    22.00   Positive Sale
3    536365         6       3.39    20.34   Positive Sale
4    536365         6       3.39    20.34   Positive Sale
5    536365         2       7.65    15.30   Positive Sale
6    536365         6       4.25    25.50   Positive Sale
7    536366         6       1.85    11.10   Positive Sale
8    536366         6       1.85    11.10   Positive Sale
9    536367        32       1.69    54.08   Positive Sale

Transaction type counts:
TransactionType
Positive Sale    530104
Cancellation       9288
Return             1336
Other/Invalid      1181
Name: count, dtype: int64

In [11]:
df_work["IsIdentifiedCustomer"] = df_work["CustomerID"].notna()

df_work[[
    "CustomerID",
    "IsIdentifiedCustomer"
]].head(10)

   CustomerID  IsIdentifiedCustomer
0     17850.0                  True
1     17850.0                  True
2     17850.0                  True
3     17850.0                  True
4     17850.0                  True
5     17850.0                  True
6     17850.0                  True
7     17850.0                  True
8     17850.0                  True
9     13047.0                  True

In [12]:
df_work["InvoiceDate"] = pd.to_datetime(
    df_work["InvoiceDate"]
)

print(df_work["InvoiceDate"].dtype)
print(df_work["InvoiceDate"].head())

datetime64[ns]
0   2010-12-01 08:26:00
1   2010-12-01 08:26:00
2   2010-12-01 08:26:00
3   2010-12-01 08:26:00
4   2010-12-01 08:26:00
Name: InvoiceDate, dtype: datetime64[ns]

In [13]:
df_work["InvoiceNo"] = df_work["InvoiceNo"].astype("string")
df_work["StockCode"] = df_work["StockCode"].astype("string")
df_work["Country"] = df_work["Country"].astype("string")

print(df_work[["InvoiceNo", "StockCode", "Country"]].dtypes)

InvoiceNo    string[python]
StockCode    string[python]
Country      string[python]
dtype: object

In [14]:
column_order = [
    "InvoiceNo",
    "InvoiceDate",
    "StockCode",
    "ProductDescription",
    "CustomerID",
    "IsIdentifiedCustomer",
    "Country",
    "Quantity",
    "UnitPrice",
    "Revenue",
    "TransactionType"
]

df_work = df_work[column_order]

print(df_work.columns.tolist())
df_work.head()

['InvoiceNo', 'InvoiceDate', 'StockCode', 'ProductDescription', 'CustomerID', 'IsIdentifiedCustomer', 'Country', 'Quantity', 'UnitPrice', 'Revenue', 'TransactionType']

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,IsIdentifiedCustomer,Country,Quantity,UnitPrice,Revenue,TransactionType
0,536365,2010-12-01 08:26:00,85123A,WHITE HANGING HEART T-LIGHT HOLDER,17850.0,True,United Kingdom,6,2.55,15.30,Positive Sale
1,536365,2010-12-01 08:26:00,71053,WHITE METAL LANTERN,17850.0,True,United Kingdom,6,3.39,20.34,Positive Sale
2,536365,2010-12-01 08:26:00,84406B,CREAM CUPID HEARTS COAT HANGER,17850.0,True,United Kingdom,8,2.75,22.00,Positive Sale
3,536365,2010-12-01 08:26:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,17850.0,True,United Kingdom,6,3.39,20.34,Positive Sale
4,536365,2010-12-01 08:26:00,84029E,RED WOOLLY HOTTIE WHITE HEART.,17850.0,True,United Kingdom,6,3.39,20.34,Positive Sale

In [15]:
df_work = df_work.sort_values(
    by=["InvoiceDate", "InvoiceNo"]
)

df_work.head()

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,IsIdentifiedCustomer,Country,Quantity,UnitPrice,Revenue,TransactionType
0,536365,2010-12-01 08:26:00,85123A,WHITE HANGING HEART T-LIGHT HOLDER,17850.0,True,United Kingdom,6,2.55,15.30,Positive Sale
1,536365,2010-12-01 08:26:00,71053,WHITE METAL LANTERN,17850.0,True,United Kingdom,6,3.39,20.34,Positive Sale
2,536365,2010-12-01 08:26:00,84406B,CREAM CUPID HEARTS COAT HANGER,17850.0,True,United Kingdom,8,2.75,22.00,Positive Sale
3,536365,2010-12-01 08:26:00,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,17850.0,True,United Kingdom,6,3.39,20.34,Positive Sale
4,536365,2010-12-01 08:26:00,84029E,RED WOOLLY HOTTIE WHITE HEART.,17850.0,True,United Kingdom,6,3.39,20.34,Positive Sale

In [16]:
df_work.reset_index(drop=True, inplace=True)

print(df_work.head())

print("\nIs the index sequential?")
print(df_work.index.equals(pd.RangeIndex(len(df_work))))

print("\nTotal rows:", len(df_work))
print("First index:", df_work.index[0])
print("Last index:", df_work.index[-1])

  InvoiceNo         InvoiceDate StockCode  \
0    536365 2010-12-01 08:26:00    85123A
1    536365 2010-12-01 08:26:00     71053
2    536365 2010-12-01 08:26:00    84406B
3    536365 2010-12-01 08:26:00    84029G
4    536365 2010-12-01 08:26:00    84029E

                    ProductDescription  CustomerID  IsIdentifiedCustomer  \
0   WHITE HANGING HEART T-LIGHT HOLDER     17850.0                  True
1                  WHITE METAL LANTERN     17850.0                  True
2       CREAM CUPID HEARTS COAT HANGER     17850.0                  True
3  KNITTED UNION FLAG HOT WATER BOTTLE     17850.0                  True
4       RED WOOLLY HOTTIE WHITE HEART.     17850.0                  True

          Country  Quantity  UnitPrice  Revenue TransactionType
0  United Kingdom         6       2.55    15.30   Positive Sale
1  United Kingdom         6       3.39    20.34   Positive Sale
2  United Kingdom         8       2.75    22.00   Positive Sale
3  United Kingdom         6       3.39    20.34   Positive Sale
4  United Kingdom         6       3.39    20.34   Positive Sale

Is the index sequential?
True

Total rows: 541909
First index: 0
Last index: 541908

In [17]:
missing_count = df_work.isnull().sum()

print(missing_count)

InvoiceNo                    0
InvoiceDate                  0
StockCode                    0
ProductDescription        1454
CustomerID              135080
IsIdentifiedCustomer         0
Country                      0
Quantity                     0
UnitPrice                    0
Revenue                      0
TransactionType              0
dtype: int64

In [18]:
missing_count = df_work.isnull().sum()

missing_percentage = (
    missing_count / len(df_work)
) * 100

print(missing_percentage.sort_values(ascending=False))

CustomerID              24.926694
ProductDescription       0.268311
InvoiceNo                0.000000
StockCode                0.000000
InvoiceDate              0.000000
IsIdentifiedCustomer     0.000000
Country                  0.000000
Quantity                 0.000000
UnitPrice                0.000000
Revenue                  0.000000
TransactionType          0.000000
dtype: float64

In [19]:
missing_report = pd.DataFrame({
    "MissingCount": df_work.isnull().sum(),
    "NonMissingCount": df_work.notnull().sum(),
    "MissingPercentage": (
        df_work.isnull().sum() / len(df_work)
    ) * 100
})

missing_report = missing_report.sort_values(
    by="MissingPercentage",
    ascending=False
)

missing_report

                      MissingCount  NonMissingCount  MissingPercentage
CustomerID                  135080           406829          24.926694
ProductDescription            1454           540455           0.268311
InvoiceNo                        0           541909           0.000000
StockCode                        0           541909           0.000000
InvoiceDate                      0           541909           0.000000
IsIdentifiedCustomer             0           541909           0.000000
Country                          0           541909           0.000000
Quantity                         0           541909           0.000000
UnitPrice                        0           541909           0.000000
Revenue                          0           541909           0.000000
TransactionType                  0           541909           0.000000

In [20]:
missing_customer_rows = df_work[
    df_work["CustomerID"].isnull()
]

print("Rows with missing CustomerID:",
      len(missing_customer_rows))

missing_customer_rows.head(10)

Rows with missing CustomerID: 135080

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,IsIdentifiedCustomer,Country,Quantity,UnitPrice,Revenue,TransactionType
622,536414,2010-12-01 11:52:00,22139,NaN,NaN,False,United Kingdom,56,0.00,0.00,Other/Invalid
1443,536544,2010-12-01 14:32:00,21773,DECORATIVE ROSE BATHROOM BOTTLE,NaN,False,United Kingdom,1,2.51,2.51,Positive Sale
1444,536544,2010-12-01 14:32:00,21774,DECORATIVE CATS BATHROOM BOTTLE,NaN,False,United Kingdom,2,2.51,5.02,Positive Sale
1445,536544,2010-12-01 14:32:00,21786,POLKADOT RAIN HAT,NaN,False,United Kingdom,4,0.85,3.40,Positive Sale
1446,536544,2010-12-01 14:32:00,21787,RAIN PONCHO RETROSPOT,NaN,False,United Kingdom,2,1.66,3.32,Positive Sale
1447,536544,2010-12-01 14:32:00,21790,VINTAGE SNAP CARDS,NaN,False,United Kingdom,9,1.66,14.94,Positive Sale
1448,536544,2010-12-01 14:32:00,21791,VINTAGE HEADS AND TAILS CARD GAME,NaN,False,United Kingdom,2,2.51,5.02,Positive Sale
1449,536544,2010-12-01 14:32:00,21801,CHRISTMAS TREE DECORATION WITH BELL,NaN,False,United Kingdom,10,0.43,4.30,Positive Sale
1450,536544,2010-12-01 14:32:00,21802,CHRISTMAS TREE HEART DECORATION,NaN,False,United Kingdom,9,0.43,3.87,Positive Sale
1451,536544,2010-12-01 14:32:00,21803,CHRISTMAS TREE STAR DECORATION,NaN,False,United Kingdom,11,0.43,4.73,Positive Sale

In [21]:
description = df_work["ProductDescription"]

missing_description_rows = df_work[
    description.isna()
    | description.astype("string").str.strip().eq("").fillna(False)
]

print("Rows with missing or blank descriptions:",
      len(missing_description_rows))

missing_description_rows.head(10)

Rows with missing or blank descriptions: 1454

,InvoiceNo,InvoiceDate,StockCode,ProductDescription,CustomerID,IsIdentifiedCustomer,Country,Quantity,UnitPrice,Revenue,TransactionType
622,536414,2010-12-01 11:52:00,22139,NaN,NaN,False,United Kingdom,56,0.0,0.0,Other/Invalid
1970,536545,2010-12-01 14:32:00,21134,NaN,NaN,False,United Kingdom,1,0.0,0.0,Other/Invalid
1971,536546,2010-12-01 14:33:00,22145,NaN,NaN,False,United Kingdom,1,0.0,0.0,Other/Invalid
1972,536547,2010-12-01 14:33:00,37509,NaN,NaN,False,United Kingdom,1,0.0,0.0,Other/Invalid
1987,536549,2010-12-01 14:34:00,85226A,NaN,NaN,False,United Kingdom,1,0.0,0.0,Other/Invalid
1988,536550,2010-12-01 14:34:00,85044,NaN,NaN,False,United Kingdom,1,0.0,0.0,Other/Invalid
2024,536552,2010-12-01 14:34:00,20950,NaN,NaN,False,United Kingdom,1,0.0,0.0,Other/Invalid
2025,536553,2010-12-01 14:35:00,37461,NaN,NaN,False,United Kingdom,3,0.0,0.0,Other/Invalid
2026,536554,2010-12-01 14:35:00,84670,NaN,NaN,False,United Kingdom,23,0.0,0.0,Other/Invalid
2406,536589,2010-12-01 16:50:00,21777,NaN,NaN,False,United Kingdom,-10,0.0,-0.0,Return

In [22]:
duplicate_count = df_work.duplicated().sum()

print("Exact duplicate rows before removal:",
      duplicate_count)

Exact duplicate rows before removal: 5268

In [23]:
rows_before = len(df_work)

df_work = df_work.drop_duplicates()

rows_after = len(df_work)

print("Rows before removal:", rows_before)
print("Duplicate rows removed:", rows_before - rows_after)
print("Rows after removal:", rows_after)

print("Remaining exact duplicates:",
      df_work.duplicated().sum())

Rows before removal: 541909
Duplicate rows removed: 5268
Rows after removal: 536641
Remaining exact duplicates: 0

In [24]:
combo_counts = (
    df_work.groupby(["InvoiceNo", "StockCode"])
    .size()
    .reset_index(name="LineCount")
)

repeated_combinations = combo_counts[
    combo_counts["LineCount"] > 1
]

print(
    "Repeated invoice-product combinations:",
    len(repeated_combinations)
)

repeated_combinations.head(10)

Repeated invoice-product combinations: 5199

    InvoiceNo StockCode  LineCount
135    536381     71270          2
519    536409     85116          2
522    536409    90199C          3
533    536412     21448          2
539    536412     21738          3
542    536412     22077          3
545    536412     22144          2
549    536412     22243          3
551    536412     22273          2
566    536412     22749          2

In [25]:
missing_before = df_work["ProductDescription"].isna().sum()

print("Missing descriptions before handling:", missing_before)

Missing descriptions before handling: 1454

In [26]:
df_work["ProductDescription"] = (
    df_work["ProductDescription"].fillna("Unknown Product")
)

print(
    "Missing descriptions after handling:",
    df_work["ProductDescription"].isna().sum()
)

print(
    "Unknown Product placeholders:",
    (df_work["ProductDescription"] == "Unknown Product").sum()
)

Missing descriptions after handling: 0
Unknown Product placeholders: 1454

In [27]:
quality_comparison = pd.DataFrame({
    "Metric": [
        "Total rows",
        "Missing values across all columns",
        "Exact duplicate rows"
    ],
    "Before cleaning": [
        len(df_raw),
        int(df_raw.isna().sum().sum()),
        int(df_raw.duplicated().sum())
    ],
    "After cleaning": [
        len(df_work),
        int(df_work.isna().sum().sum()),
        int(df_work.duplicated().sum())
    ]
})

quality_comparison

                              Metric  Before cleaning  After cleaning
0                         Total rows           541909          536641
1  Missing values across all columns           136534          135037
2               Exact duplicate rows             5268               0